"""
Management command to seed real Kenyan educational institutions.
Covers all 47 counties starting from Mombasa (001).
Includes Primary Schools, Secondary Schools, Universities, and Colleges.

Usage:
    python manage.py seed_institutions

Place this file at:
    main_application/management/commands/seed_institutions.py
"""

from django.core.management.base import BaseCommand
from django.db import transaction


class Command(BaseCommand):
    help = 'Seed real Kenyan educational institutions across all counties'

    def add_arguments(self, parser):
        parser.add_argument('--skip-delete', action='store_true', help='Skip deleting existing institutions')
        parser.add_argument('--county', type=str, help='Seed only a specific county (e.g. "Mombasa")')

    def handle(self, *args, **options):
        from main_application.models import Institution, County

        if not options['skip_delete']:
            self.stdout.write(self.style.WARNING('🗑️  Deleting all existing institutions...'))
            count = Institution.objects.all().count()
            Institution.objects.all().delete()
            self.stdout.write(self.style.SUCCESS(f'   Deleted {count} institutions.'))

        self.stdout.write(self.style.MIGRATE_HEADING('🏫 Seeding Kenyan institutions...'))

        all_institutions = self._get_all_institutions()

        filter_county = options.get('county')
        if filter_county:
            all_institutions = [i for i in all_institutions if i.get('county_name', '').lower() == filter_county.lower()]

        created_count = 0
        skipped_count = 0

        with transaction.atomic():
            for inst_data in all_institutions:
                county_name = inst_data.pop('county_name', None)
                county_code = inst_data.pop('county_code', None)

                # Get or skip if county not found
                county = None
                if county_name:
                    try:
                        county = County.objects.filter(name__icontains=county_name).first()
                        if not county and county_code:
                            county = County.objects.filter(code=county_code).first()
                    except Exception:
                        pass

                try:
                    inst, created = Institution.objects.get_or_create(
                        name=inst_data['name'],
                        defaults={**inst_data, 'county': county}
                    )
                    if created:
                        created_count += 1
                    else:
                        skipped_count += 1
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'   Skipped {inst_data.get("name", "?")} : {e}'))
                    skipped_count += 1

        self.stdout.write(self.style.SUCCESS(
            f'\n✅ Done! Created: {created_count} | Skipped/existing: {skipped_count} | Total attempted: {len(all_institutions)}'
        ))

    def _get_all_institutions(self):
        """Returns all institutions data. County code maps: 001=Mombasa, 002=Kwale, etc."""
        return (
            self._primary_schools() +
            self._secondary_schools() +
            self._universities() +
            self._colleges_and_tvets()
        )

    # =========================================================
    # PRIMARY SCHOOLS
    # =========================================================
    def _primary_schools(self):
        return [
            # ── MOMBASA (001) ──────────────────────────────────────
            {'name': 'Aga Khan Primary School Mombasa', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312345', 'email': 'agakhanpri.msa@schools.go.ke', 'is_active': True},
            {'name': 'Jaffery Academy Mombasa', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312346', 'email': 'jaffery.msa@schools.go.ke', 'is_active': True},
            {'name': 'Dr. Ribeiro Parklands Primary', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Nyali', 'phone_number': '+254412312347', 'email': 'ribeiro.msa@schools.go.ke', 'is_active': True},
            {'name': 'Shimo La Tewa Primary School', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Kisauni', 'phone_number': '+254412312348', 'email': 'shimo.pri@schools.go.ke', 'is_active': True},
            {'name': 'Likoni Primary School', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Likoni', 'phone_number': '+254412312349', 'email': 'likoni.pri@schools.go.ke', 'is_active': True},
            {'name': 'Bomu Primary School', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Changamwe', 'phone_number': '+254412312350', 'email': 'bomu.pri@schools.go.ke', 'is_active': True},
            {'name': 'Mombasa Primary School', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312351', 'email': 'mombasa.pri@schools.go.ke', 'is_active': True},
            {'name': 'Tudor Primary School', 'institution_type': 'primary', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312352', 'email': 'tudor.pri@schools.go.ke', 'is_active': True},

            # ── KWALE (002) ────────────────────────────────────────
            {'name': 'Ukunda Primary School', 'institution_type': 'primary', 'county_name': 'Kwale', 'county_code': '002', 'sub_county': 'Msambweni', 'phone_number': '+254401234001', 'email': 'ukunda.pri@schools.go.ke', 'is_active': True},
            {'name': 'Diani Primary School', 'institution_type': 'primary', 'county_name': 'Kwale', 'county_code': '002', 'sub_county': 'Msambweni', 'phone_number': '+254401234002', 'email': 'diani.pri@schools.go.ke', 'is_active': True},
            {'name': 'Kwale Primary School', 'institution_type': 'primary', 'county_name': 'Kwale', 'county_code': '002', 'sub_county': 'Kwale', 'phone_number': '+254401234003', 'email': 'kwale.pri@schools.go.ke', 'is_active': True},

            # ── KILIFI (003) ───────────────────────────────────────
            {'name': 'Kilifi Primary School', 'institution_type': 'primary', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Kilifi North', 'phone_number': '+254412200001', 'email': 'kilifi.pri@schools.go.ke', 'is_active': True},
            {'name': 'Malindi Primary School', 'institution_type': 'primary', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Malindi', 'phone_number': '+254412200002', 'email': 'malindi.pri@schools.go.ke', 'is_active': True},
            {'name': 'Watamu Primary School', 'institution_type': 'primary', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Malindi', 'phone_number': '+254412200003', 'email': 'watamu.pri@schools.go.ke', 'is_active': True},

            # ── TANA RIVER (004) ───────────────────────────────────
            {'name': 'Hola Primary School', 'institution_type': 'primary', 'county_name': 'Tana River', 'county_code': '004', 'sub_county': 'Bura', 'phone_number': '+254467200001', 'email': 'hola.pri@schools.go.ke', 'is_active': True},
            {'name': 'Garsen Primary School', 'institution_type': 'primary', 'county_name': 'Tana River', 'county_code': '004', 'sub_county': 'Garsen', 'phone_number': '+254467200002', 'email': 'garsen.pri@schools.go.ke', 'is_active': True},

            # ── LAMU (005) ─────────────────────────────────────────
            {'name': 'Lamu Primary School', 'institution_type': 'primary', 'county_name': 'Lamu', 'county_code': '005', 'sub_county': 'Lamu East', 'phone_number': '+254421400001', 'email': 'lamu.pri@schools.go.ke', 'is_active': True},
            {'name': 'Mokowe Primary School', 'institution_type': 'primary', 'county_name': 'Lamu', 'county_code': '005', 'sub_county': 'Lamu West', 'phone_number': '+254421400002', 'email': 'mokowe.pri@schools.go.ke', 'is_active': True},

            # ── TAITA-TAVETA (006) ─────────────────────────────────
            {'name': 'Voi Primary School', 'institution_type': 'primary', 'county_name': 'Taita-Taveta', 'county_code': '006', 'sub_county': 'Voi', 'phone_number': '+254435200001', 'email': 'voi.pri@schools.go.ke', 'is_active': True},
            {'name': 'Wundanyi Primary School', 'institution_type': 'primary', 'county_name': 'Taita-Taveta', 'county_code': '006', 'sub_county': 'Wundanyi', 'phone_number': '+254435200002', 'email': 'wundanyi.pri@schools.go.ke', 'is_active': True},

            # ── NAIROBI (047) ──────────────────────────────────────
            {'name': 'Nairobi Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202312001', 'email': 'nairobi.pri@schools.go.ke', 'is_active': True},
            {'name': 'Lavington Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202312002', 'email': 'lavington.pri@schools.go.ke', 'is_active': True},
            {'name': 'Highridge Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202312003', 'email': 'highridge.pri@schools.go.ke', 'is_active': True},
            {'name': 'Upper Hill Primary School Nairobi', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Langata', 'phone_number': '+254202312004', 'email': 'upperhill.pri@schools.go.ke', 'is_active': True},
            {'name': 'Olympic Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kibra', 'phone_number': '+254202312005', 'email': 'olympic.pri@schools.go.ke', 'is_active': True},
            {'name': 'Pangani Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Mathare', 'phone_number': '+254202312006', 'email': 'pangani.pri@schools.go.ke', 'is_active': True},
            {'name': 'Westlands Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202312007', 'email': 'westlands.pri@schools.go.ke', 'is_active': True},
            {'name': 'Pumwani Primary School', 'institution_type': 'primary', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kamukunji', 'phone_number': '+254202312008', 'email': 'pumwani.pri@schools.go.ke', 'is_active': True},

            # ── KIAMBU (022 area / actual 022 is Muranga, Kiambu=036) ──
            {'name': 'Thika Road Primary School', 'institution_type': 'primary', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254672312001', 'email': 'thikaroad.pri@schools.go.ke', 'is_active': True},
            {'name': 'Ruiru Primary School', 'institution_type': 'primary', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Ruiru', 'phone_number': '+254672312002', 'email': 'ruiru.pri@schools.go.ke', 'is_active': True},

            # ── NAKURU (032) ───────────────────────────────────────
            {'name': 'Nakuru Primary School', 'institution_type': 'primary', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town East', 'phone_number': '+254512312001', 'email': 'nakuru.pri@schools.go.ke', 'is_active': True},
            {'name': 'Naivasha Primary School', 'institution_type': 'primary', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Naivasha', 'phone_number': '+254512312002', 'email': 'naivasha.pri@schools.go.ke', 'is_active': True},

            # ── KISUMU (040) ───────────────────────────────────────
            {'name': 'Kisumu Primary School', 'institution_type': 'primary', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312001', 'email': 'kisumu.pri@schools.go.ke', 'is_active': True},
            {'name': 'Ogada Primary School', 'institution_type': 'primary', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu East', 'phone_number': '+254572312002', 'email': 'ogada.pri@schools.go.ke', 'is_active': True},

            # ── MERU (021) ─────────────────────────────────────────
            {'name': 'Meru Primary School', 'institution_type': 'primary', 'county_name': 'Meru', 'county_code': '021', 'sub_county': 'Imenti North', 'phone_number': '+254642312001', 'email': 'meru.pri@schools.go.ke', 'is_active': True},
            {'name': 'Nkubu Primary School', 'institution_type': 'primary', 'county_name': 'Meru', 'county_code': '021', 'sub_county': 'Imenti South', 'phone_number': '+254642312002', 'email': 'nkubu.pri@schools.go.ke', 'is_active': True},

            # ── EMBU (014) ─────────────────────────────────────────
            {'name': 'Embu Primary School', 'institution_type': 'primary', 'county_name': 'Embu', 'county_code': '014', 'sub_county': 'Embu Town', 'phone_number': '+254682312001', 'email': 'embu.pri@schools.go.ke', 'is_active': True},
            {'name': 'Runyenjes Primary School', 'institution_type': 'primary', 'county_name': 'Embu', 'county_code': '014', 'sub_county': 'Runyenjes', 'phone_number': '+254682312002', 'email': 'runyenjes.pri@schools.go.ke', 'is_active': True},

            # ── NYERI (037) ────────────────────────────────────────
            {'name': 'Nyeri Primary School', 'institution_type': 'primary', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Nyeri Town', 'phone_number': '+254612312001', 'email': 'nyeri.pri@schools.go.ke', 'is_active': True},
            {'name': 'Karatina Primary School', 'institution_type': 'primary', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312002', 'email': 'karatina.pri@schools.go.ke', 'is_active': True},
            {'name': 'Othaya Primary School', 'institution_type': 'primary', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Othaya', 'phone_number': '+254612312003', 'email': 'othaya.pri@schools.go.ke', 'is_active': True},
        ]

    # =========================================================
    # SECONDARY SCHOOLS
    # =========================================================
    def _secondary_schools(self):
        return [
            # ── NATIONAL SCHOOLS ──────────────────────────────────
            # Nairobi
            {'name': 'Alliance High School', 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Kikuyu', 'phone_number': '+254670521002', 'email': 'principal@alliance.ac.ke', 'principal_name': 'Mr. Fredrick Kariuki', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kikuyu Branch', 'account_number': 'ACC1000001', 'account_name': 'Alliance High School', 'is_active': True},
            {'name': 'Nairobi School', 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Dagoretti North', 'phone_number': '+254202722682', 'email': 'principal@nairobischool.ac.ke', 'principal_name': 'Mr. Joseph Mwangi', 'bank_name': 'Equity Bank', 'bank_branch': 'Lavington', 'account_number': 'ACC1000002', 'account_name': 'Nairobi School', 'is_active': True},
            {'name': 'Kenya High School', 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202712432', 'email': 'principal@kenyahigh.ac.ke', 'principal_name': 'Mrs. Jane Kamau', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Westlands', 'account_number': 'ACC1000003', 'account_name': 'Kenya High School', 'is_active': True},
            {'name': 'Lenana School', 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Langata', 'phone_number': '+254202714755', 'email': 'principal@lenana.ac.ke', 'principal_name': 'Mr. Peter Njoroge', 'bank_name': 'Barclays Bank Kenya', 'bank_branch': 'Karen', 'account_number': 'ACC1000004', 'account_name': 'Lenana School', 'is_active': True},
            {'name': 'Mang\'u High School', 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Gatundu South', 'phone_number': '+254672312001', 'email': 'principal@mangu.ac.ke', 'principal_name': 'Mr. James Githinji', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Thika', 'account_number': 'ACC1000005', 'account_name': "Mang'u High School", 'is_active': True},
            {'name': 'Starehe Boys Centre', 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202216026', 'email': 'principal@starehe.ac.ke', 'principal_name': 'Mr. Geoffrey Gateri', 'bank_name': 'Equity Bank', 'bank_branch': 'Starehe', 'account_number': 'ACC1000006', 'account_name': 'Starehe Boys Centre', 'is_active': True},
            {'name': 'Upper Hill School', 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Langata', 'phone_number': '+254202714321', 'email': 'principal@upperhill.ac.ke', 'principal_name': 'Mr. Josephat Mutua', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Upper Hill', 'account_number': 'ACC1000007', 'account_name': 'Upper Hill School', 'is_active': True},
            {'name': 'Limuru Girls High School', 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Limuru', 'phone_number': '+254672312010', 'email': 'principal@limurugirlshigh.ac.ke', 'principal_name': 'Mrs. Mary Wambui', 'bank_name': 'Family Bank', 'bank_branch': 'Limuru', 'account_number': 'ACC1000008', 'account_name': 'Limuru Girls High School', 'is_active': True},
            {'name': 'Kabarak High School', 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Subukia', 'phone_number': '+254512312020', 'email': 'principal@kabarakhigh.ac.ke', 'principal_name': 'Mr. Reuben Rop', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000009', 'account_name': 'Kabarak High School', 'is_active': True},
            {'name': "St. Mary's School Nairobi", 'institution_type': 'highschool', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202714200', 'email': 'principal@stmarysnairobi.ac.ke', 'principal_name': 'Br. Peter Musyoka', 'bank_name': 'Barclays Bank Kenya', 'bank_branch': 'Westlands', 'account_number': 'ACC1000010', 'account_name': "St. Mary's School Nairobi", 'is_active': True},
            {'name': 'Kiambu High School', 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Kiambu Town', 'phone_number': '+254672312020', 'email': 'principal@kiambuhigh.ac.ke', 'principal_name': 'Mr. John Kariuki', 'bank_name': 'Equity Bank', 'bank_branch': 'Kiambu', 'account_number': 'ACC1000011', 'account_name': 'Kiambu High School', 'is_active': True},
            {'name': 'Kangaru School', 'institution_type': 'highschool', 'county_name': 'Embu', 'county_code': '014', 'sub_county': 'Manyatta', 'phone_number': '+254682312020', 'email': 'principal@kangaruschool.ac.ke', 'principal_name': 'Mr. Stephen Gitonga', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Embu', 'account_number': 'ACC1000012', 'account_name': 'Kangaru School', 'is_active': True},
            {'name': 'Chogoria Boys High School', 'institution_type': 'highschool', 'county_name': 'Tharaka-Nithi', 'county_code': '016', 'sub_county': 'Maara', 'phone_number': '+254642412001', 'email': 'principal@chogoriahigh.ac.ke', 'principal_name': 'Mr. David Mwiti', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Chogoria', 'account_number': 'ACC1000013', 'account_name': 'Chogoria Boys High School', 'is_active': True},
            {'name': "St. George's Girls High School Mombasa", 'institution_type': 'highschool', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412230001', 'email': 'principal@stgeorgesmsa.ac.ke', 'principal_name': 'Mrs. Susan Karanja', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Mombasa', 'account_number': 'ACC1000014', 'account_name': "St. George's Girls High School", 'is_active': True},
            {'name': "Shimo La Tewa High School", 'institution_type': 'highschool', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Kisauni', 'phone_number': '+254412230002', 'email': 'principal@shimolatewa.ac.ke', 'principal_name': 'Mr. Omar Hassan', 'bank_name': 'Equity Bank', 'bank_branch': 'Mombasa', 'account_number': 'ACC1000015', 'account_name': 'Shimo La Tewa High School', 'is_active': True},
            {'name': 'Aga Khan High School Mombasa', 'institution_type': 'highschool', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412230003', 'email': 'principal@agakhanhigh.msa.ac.ke', 'principal_name': 'Mr. Roshan Alibhai', 'bank_name': 'Barclays Bank Kenya', 'bank_branch': 'Mombasa', 'account_number': 'ACC1000016', 'account_name': 'Aga Khan High School Mombasa', 'is_active': True},
            {'name': 'Laiser Hill Academy', 'institution_type': 'highschool', 'county_name': 'Kajiado', 'county_code': '034', 'sub_county': 'Kajiado North', 'phone_number': '+254452312001', 'email': 'principal@laiserhill.ac.ke', 'principal_name': 'Mrs. Grace Tipape', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kitengela', 'account_number': 'ACC1000017', 'account_name': 'Laiser Hill Academy', 'is_active': True},
            {'name': 'Machakos High School', 'institution_type': 'highschool', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312001', 'email': 'principal@machakoshigh.ac.ke', 'principal_name': 'Mr. Francis Mutua', 'bank_name': 'Equity Bank', 'bank_branch': 'Machakos', 'account_number': 'ACC1000018', 'account_name': 'Machakos High School', 'is_active': True},
            {'name': "Moi Girls' High School Eldoret", 'institution_type': 'highschool', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret East', 'phone_number': '+254532312001', 'email': 'principal@moigirls.eldoret.ac.ke', 'principal_name': 'Mrs. Jemimah Chebii', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Eldoret', 'account_number': 'ACC1000019', 'account_name': "Moi Girls' High School Eldoret", 'is_active': True},
            {'name': "Moi High School Kabarak", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Subukia', 'phone_number': '+254512312030', 'email': 'principal@moihighkabarak.ac.ke', 'principal_name': 'Mr. Eliud Rono', 'bank_name': 'Equity Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000020', 'account_name': 'Moi High School Kabarak', 'is_active': True},
            {'name': "Friends School Kamusinga", 'institution_type': 'highschool', 'county_name': 'Kakamega', 'county_code': '031', 'sub_county': 'Lugari', 'phone_number': '+254562312001', 'email': 'principal@kamusinga.ac.ke', 'principal_name': 'Mr. Laban Amukhale', 'bank_name': 'Family Bank', 'bank_branch': 'Kakamega', 'account_number': 'ACC1000021', 'account_name': 'Friends School Kamusinga', 'is_active': True},
            {'name': "Kakamega High School", 'institution_type': 'highschool', 'county_name': 'Kakamega', 'county_code': '031', 'sub_county': 'Lurambi', 'phone_number': '+254562312002', 'email': 'principal@kakamegahigh.ac.ke', 'principal_name': 'Mr. Benjamin Wanyonyi', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kakamega', 'account_number': 'ACC1000022', 'account_name': 'Kakamega High School', 'is_active': True},
            {'name': "Kisumu Boys High School", 'institution_type': 'highschool', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312010', 'email': 'principal@kisumuboys.ac.ke', 'principal_name': 'Mr. Paul Ochieng', 'bank_name': 'Equity Bank', 'bank_branch': 'Kisumu', 'account_number': 'ACC1000023', 'account_name': 'Kisumu Boys High School', 'is_active': True},
            {'name': "Kisumu Girls High School", 'institution_type': 'highschool', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312011', 'email': 'principal@kisumugirls.ac.ke', 'principal_name': 'Mrs. Carolyne Otieno', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisumu', 'account_number': 'ACC1000024', 'account_name': 'Kisumu Girls High School', 'is_active': True},
            {'name': "Maseno School", 'institution_type': 'highschool', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Seme', 'phone_number': '+254572312012', 'email': 'principal@masenoschool.ac.ke', 'principal_name': 'Mr. Ayub Okoth', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Maseno', 'account_number': 'ACC1000025', 'account_name': 'Maseno School', 'is_active': True},
            {'name': "Nyeri High School", 'institution_type': 'highschool', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Nyeri Town', 'phone_number': '+254612312010', 'email': 'principal@nyerihigh.ac.ke', 'principal_name': 'Mr. Samuel Gatheru', 'bank_name': 'Equity Bank', 'bank_branch': 'Nyeri', 'account_number': 'ACC1000026', 'account_name': 'Nyeri High School', 'is_active': True},
            {'name': "Thika High School", 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254672312030', 'email': 'principal@thikahigh.ac.ke', 'principal_name': 'Mr. Kenneth Kago', 'bank_name': 'Family Bank', 'bank_branch': 'Thika', 'account_number': 'ACC1000027', 'account_name': 'Thika High School', 'is_active': True},
            {'name': "Njiiri School", 'institution_type': 'highschool', 'county_name': "Murang'a", 'county_code': '022', 'sub_county': 'Gatanga', 'phone_number': '+254721312001', 'email': 'principal@njirischool.ac.ke', 'principal_name': 'Mr. James Gatheu', 'bank_name': 'Co-operative Bank', 'bank_branch': "Murang'a", 'account_number': 'ACC1000028', 'account_name': 'Njiiri School', 'is_active': True},
            {'name': "Kerugoya Boys High School", 'institution_type': 'highschool', 'county_name': 'Kirinyaga', 'county_code': '020', 'sub_county': 'Kirinyaga Central', 'phone_number': '+254602312001', 'email': 'principal@kerugoyahigh.ac.ke', 'principal_name': 'Mr. Lawrence Wachira', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kerugoya', 'account_number': 'ACC1000029', 'account_name': 'Kerugoya Boys High School', 'is_active': True},
            {'name': "Nakuru High School", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town West', 'phone_number': '+254512312040', 'email': 'principal@nakuruhigh.ac.ke', 'principal_name': 'Mr. Robert Mwangi', 'bank_name': 'Equity Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000030', 'account_name': 'Nakuru High School', 'is_active': True},
            {'name': 'Eldoret High School', 'institution_type': 'highschool', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret East', 'phone_number': '+254532312010', 'email': 'principal@eldorethigh.ac.ke', 'principal_name': 'Mr. Kiprotich Rono', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Eldoret', 'account_number': 'ACC1000031', 'account_name': 'Eldoret High School', 'is_active': True},
            {'name': "Kipsigis Girls High School", 'institution_type': 'highschool', 'county_name': 'Kericho', 'county_code': '029', 'sub_county': 'Belgut', 'phone_number': '+254522312001', 'email': 'principal@kipsigisgirls.ac.ke', 'principal_name': 'Mrs. Esther Kibor', 'bank_name': 'Family Bank', 'bank_branch': 'Kericho', 'account_number': 'ACC1000032', 'account_name': 'Kipsigis Girls High School', 'is_active': True},
            {'name': "Kericho High School", 'institution_type': 'highschool', 'county_name': 'Kericho', 'county_code': '029', 'sub_county': 'Kericho', 'phone_number': '+254522312002', 'email': 'principal@kerichohigh.ac.ke', 'principal_name': 'Mr. Alex Kirui', 'bank_name': 'Equity Bank', 'bank_branch': 'Kericho', 'account_number': 'ACC1000033', 'account_name': 'Kericho High School', 'is_active': True},
            {'name': "Kisii High School", 'institution_type': 'highschool', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312001', 'email': 'principal@kisiihigh.ac.ke', 'principal_name': 'Mr. Bernard Ongaro', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kisii', 'account_number': 'ACC1000034', 'account_name': 'Kisii High School', 'is_active': True},
            {'name': "Nyabururu Girls High School", 'institution_type': 'highschool', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312002', 'email': 'principal@nyabururu.ac.ke', 'principal_name': 'Mrs. Phyllis Nyakundi', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisii', 'account_number': 'ACC1000035', 'account_name': 'Nyabururu Girls High School', 'is_active': True},
            {'name': "Meru School", 'institution_type': 'highschool', 'county_name': 'Meru', 'county_code': '021', 'sub_county': 'Imenti North', 'phone_number': '+254642312010', 'email': 'principal@meruschool.ac.ke', 'principal_name': 'Mr. George Murungi', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Meru', 'account_number': 'ACC1000036', 'account_name': 'Meru School', 'is_active': True},
            {'name': "Nkabune Technical School", 'institution_type': 'highschool', 'county_name': 'Meru', 'county_code': '021', 'sub_county': 'Imenti North', 'phone_number': '+254642312011', 'email': 'principal@nkabune.ac.ke', 'principal_name': 'Mr. Isaac Mugambi', 'bank_name': 'Equity Bank', 'bank_branch': 'Meru', 'account_number': 'ACC1000037', 'account_name': 'Nkabune Technical School', 'is_active': True},
            {'name': "Malindi High School", 'institution_type': 'highschool', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Malindi', 'phone_number': '+254422312001', 'email': 'principal@malindihigh.ac.ke', 'principal_name': 'Mr. Hamisi Mwambire', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Malindi', 'account_number': 'ACC1000038', 'account_name': 'Malindi High School', 'is_active': True},
            {'name': "Mombasa High School", 'institution_type': 'highschool', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412230010', 'email': 'principal@mombasahigh.ac.ke', 'principal_name': 'Mr. Abdullah Rashid', 'bank_name': 'Equity Bank', 'bank_branch': 'Mombasa', 'account_number': 'ACC1000039', 'account_name': 'Mombasa High School', 'is_active': True},
            {'name': "Coast Girls High School", 'institution_type': 'highschool', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412230011', 'email': 'principal@coastgirls.ac.ke', 'principal_name': 'Mrs. Fatuma Ali', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Mombasa', 'account_number': 'ACC1000040', 'account_name': 'Coast Girls High School', 'is_active': True},
            {'name': "Kitui High School", 'institution_type': 'highschool', 'county_name': 'Kitui', 'county_code': '015', 'sub_county': 'Kitui Central', 'phone_number': '+254462312001', 'email': 'principal@kituihigh.ac.ke', 'principal_name': 'Mr. Cyrus Mutunga', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kitui', 'account_number': 'ACC1000041', 'account_name': 'Kitui High School', 'is_active': True},
            {'name': "Machakos Girls High School", 'institution_type': 'highschool', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312010', 'email': 'principal@machakosgirls.ac.ke', 'principal_name': 'Mrs. Monica Muema', 'bank_name': 'Equity Bank', 'bank_branch': 'Machakos', 'account_number': 'ACC1000042', 'account_name': 'Machakos Girls High School', 'is_active': True},
            {'name': "Makueni Girls High School", 'institution_type': 'highschool', 'county_name': 'Makueni', 'county_code': '017', 'sub_county': 'Makueni', 'phone_number': '+254452312010', 'email': 'principal@makuenigirls.ac.ke', 'principal_name': 'Mrs. Lydiah Kioko', 'bank_name': 'Family Bank', 'bank_branch': 'Wote', 'account_number': 'ACC1000043', 'account_name': 'Makueni Girls High School', 'is_active': True},
            {'name': "Thika Girls High School", 'institution_type': 'highschool', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254672312040', 'email': 'principal@thikagirls.ac.ke', 'principal_name': 'Mrs. Alice Wanjiru', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Thika', 'account_number': 'ACC1000044', 'account_name': 'Thika Girls High School', 'is_active': True},
            {'name': "Kagumo High School", 'institution_type': 'highschool', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312020', 'email': 'principal@kagumohigh.ac.ke', 'principal_name': 'Mr. David Wanyiri', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Karatina', 'account_number': 'ACC1000045', 'account_name': 'Kagumo High School', 'is_active': True},
            {'name': "Giakanja High School", 'institution_type': 'highschool', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312021', 'email': 'principal@giakanjahigh.ac.ke', 'principal_name': 'Mr. Nicholas Githinji', 'bank_name': 'Equity Bank', 'bank_branch': 'Nyeri', 'account_number': 'ACC1000046', 'account_name': 'Giakanja High School', 'is_active': True},
            {'name': "Ngandu Girls High School", 'institution_type': 'highschool', 'county_name': 'Kirinyaga', 'county_code': '020', 'sub_county': 'Mwea', 'phone_number': '+254602312010', 'email': 'principal@ngandugirls.ac.ke', 'principal_name': 'Mrs. Beatrice Mugo', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kerugoya', 'account_number': 'ACC1000047', 'account_name': 'Ngandu Girls High School', 'is_active': True},
            {'name': "Baraton Academy", 'institution_type': 'highschool', 'county_name': 'Nandi', 'county_code': '030', 'sub_county': 'Tinderet', 'phone_number': '+254542312001', 'email': 'principal@baraton.ac.ke', 'principal_name': 'Dr. Florence Maina', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Eldoret', 'account_number': 'ACC1000048', 'account_name': 'Baraton Academy', 'is_active': True},
            {'name': "Kabianga High School", 'institution_type': 'highschool', 'county_name': 'Kericho', 'county_code': '029', 'sub_county': 'Kericho', 'phone_number': '+254522312010', 'email': 'principal@kabianghigh.ac.ke', 'principal_name': 'Mr. Julius Mutai', 'bank_name': 'Equity Bank', 'bank_branch': 'Kericho', 'account_number': 'ACC1000049', 'account_name': 'Kabianga High School', 'is_active': True},
            {'name': "Kisii School", 'institution_type': 'highschool', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312010', 'email': 'principal@kisii.sch.ac.ke', 'principal_name': 'Mr. Kennedy Abuga', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kisii', 'account_number': 'ACC1000050', 'account_name': 'Kisii School', 'is_active': True},
            {'name': "Bondo High School", 'institution_type': 'highschool', 'county_name': 'Siaya', 'county_code': '041', 'sub_county': 'Bondo', 'phone_number': '+254592312001', 'email': 'principal@bondohigh.ac.ke', 'principal_name': 'Mr. Hezron Ogolla', 'bank_name': 'Family Bank', 'bank_branch': 'Bondo', 'account_number': 'ACC1000051', 'account_name': 'Bondo High School', 'is_active': True},
            {'name': "Ng'iya Girls High School", 'institution_type': 'highschool', 'county_name': 'Siaya', 'county_code': '041', 'sub_county': 'Ugenya', 'phone_number': '+254592312002', 'email': 'principal@ngiyas.ac.ke', 'principal_name': 'Mrs. Lilian Achieng', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Siaya', 'account_number': 'ACC1000052', 'account_name': "Ng'iya Girls High School", 'is_active': True},
            {'name': "Butere High School", 'institution_type': 'highschool', 'county_name': 'Kakamega', 'county_code': '031', 'sub_county': 'Butere', 'phone_number': '+254562312010', 'email': 'principal@buterehigh.ac.ke', 'principal_name': 'Mr. Silas Eshitera', 'bank_name': 'Equity Bank', 'bank_branch': 'Butere', 'account_number': 'ACC1000053', 'account_name': 'Butere High School', 'is_active': True},
            {'name': "Nambale High School", 'institution_type': 'highschool', 'county_name': 'Busia', 'county_code': '039', 'sub_county': 'Nambale', 'phone_number': '+254552312001', 'email': 'principal@nambalehigh.ac.ke', 'principal_name': 'Mr. Philip Wafula', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Busia', 'account_number': 'ACC1000054', 'account_name': 'Nambale High School', 'is_active': True},
            {'name': "Friends School Kaimosi", 'institution_type': 'highschool', 'county_name': 'Vihiga', 'county_code': '038', 'sub_county': 'Hamisi', 'phone_number': '+254562412001', 'email': 'principal@kaimosi.ac.ke', 'principal_name': 'Mr. Emmanuel Shikuku', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kakamega', 'account_number': 'ACC1000055', 'account_name': 'Friends School Kaimosi', 'is_active': True},
            {'name': "Kapkenda Girls High School", 'institution_type': 'highschool', 'county_name': 'Elgeyo-Marakwet', 'county_code': '028', 'sub_county': 'Keiyo North', 'phone_number': '+254532412001', 'email': 'principal@kapkenda.ac.ke', 'principal_name': 'Mrs. Hellen Chepkemoi', 'bank_name': 'Equity Bank', 'bank_branch': 'Iten', 'account_number': 'ACC1000056', 'account_name': 'Kapkenda Girls High School', 'is_active': True},
            {'name': "St. Brigid's Asumbi Girls", 'institution_type': 'highschool', 'county_name': 'Homa Bay', 'county_code': '043', 'sub_county': 'Rachuonyo South', 'phone_number': '+254592412001', 'email': 'principal@asumbi.ac.ke', 'principal_name': 'Sr. Mary Omondi', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kendu Bay', 'account_number': 'ACC1000057', 'account_name': "St. Brigid's Asumbi Girls", 'is_active': True},
            {'name': "Ndhiwa High School", 'institution_type': 'highschool', 'county_name': 'Homa Bay', 'county_code': '043', 'sub_county': 'Ndhiwa', 'phone_number': '+254592412002', 'email': 'principal@ndhiwahigh.ac.ke', 'principal_name': 'Mr. Joseph Nyamori', 'bank_name': 'Equity Bank', 'bank_branch': 'Homa Bay', 'account_number': 'ACC1000058', 'account_name': 'Ndhiwa High School', 'is_active': True},
            {'name': "Migori High School", 'institution_type': 'highschool', 'county_name': 'Migori', 'county_code': '044', 'sub_county': 'Suna East', 'phone_number': '+254592512001', 'email': 'principal@migorihigh.ac.ke', 'principal_name': 'Mr. Duncan Odhiambo', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Migori', 'account_number': 'ACC1000059', 'account_name': 'Migori High School', 'is_active': True},
            {'name': "Kisii Girls High School", 'institution_type': 'highschool', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312020', 'email': 'principal@kisiigirls.ac.ke', 'principal_name': 'Mrs. Alice Momanyi', 'bank_name': 'Family Bank', 'bank_branch': 'Kisii', 'account_number': 'ACC1000060', 'account_name': 'Kisii Girls High School', 'is_active': True},
            {'name': "Sironga Girls High School", 'institution_type': 'highschool', 'county_name': 'Nyamira', 'county_code': '046', 'sub_county': 'Manga', 'phone_number': '+254582412001', 'email': 'principal@sirongagirls.ac.ke', 'principal_name': 'Mrs. Damaris Nyakundi', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nyamira', 'account_number': 'ACC1000061', 'account_name': 'Sironga Girls High School', 'is_active': True},
            {'name': "Nakuru Girls High School", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town East', 'phone_number': '+254512312050', 'email': 'principal@nakurugirls.ac.ke', 'principal_name': 'Mrs. Josephine Waweru', 'bank_name': 'Equity Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000062', 'account_name': 'Nakuru Girls High School', 'is_active': True},
            {'name': "Kereri Girls High School", 'institution_type': 'highschool', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312030', 'email': 'principal@kererigirls.ac.ke', 'principal_name': 'Mrs. Penina Ongeri', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisii', 'account_number': 'ACC1000063', 'account_name': 'Kereri Girls High School', 'is_active': True},
            {'name': "Rift Valley Academy", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Subukia', 'phone_number': '+254512312060', 'email': 'principal@rva.ac.ke', 'principal_name': 'Mr. Tom Ogola', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000064', 'account_name': 'Rift Valley Academy', 'is_active': True},
            {'name': "Maranda High School", 'institution_type': 'highschool', 'county_name': 'Siaya', 'county_code': '041', 'sub_county': 'Ugenya', 'phone_number': '+254592312010', 'email': 'principal@maranda.ac.ke', 'principal_name': 'Mr. Felix Ouma', 'bank_name': 'Equity Bank', 'bank_branch': 'Siaya', 'account_number': 'ACC1000065', 'account_name': 'Maranda High School', 'is_active': True},
            {'name': "Booker Academy", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town West', 'phone_number': '+254512312070', 'email': 'principal@bookeracademy.ac.ke', 'principal_name': 'Mr. Samuel Kimani', 'bank_name': 'Family Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000066', 'account_name': 'Booker Academy', 'is_active': True},
            {'name': "Butula Boys High School", 'institution_type': 'highschool', 'county_name': 'Busia', 'county_code': '039', 'sub_county': 'Butula', 'phone_number': '+254552312010', 'email': 'principal@butulahigh.ac.ke', 'principal_name': 'Mr. Cyprian Omuha', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Busia', 'account_number': 'ACC1000067', 'account_name': 'Butula Boys High School', 'is_active': True},
            {'name': "Masaa Mixed Day Secondary", 'institution_type': 'highschool', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu West', 'phone_number': '+254572312020', 'email': 'principal@masaasecondary.ac.ke', 'principal_name': 'Mr. Victor Odhiambo', 'bank_name': 'Equity Bank', 'bank_branch': 'Kisumu', 'account_number': 'ACC1000068', 'account_name': 'Masaa Mixed Day Secondary', 'is_active': True},
            {'name': "Mbita High School", 'institution_type': 'highschool', 'county_name': 'Homa Bay', 'county_code': '043', 'sub_county': 'Mbita', 'phone_number': '+254592412010', 'email': 'principal@mbitahigh.ac.ke', 'principal_name': 'Mr. Charles Onyango', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Homa Bay', 'account_number': 'ACC1000069', 'account_name': 'Mbita High School', 'is_active': True},
            {'name': "Turbo High School", 'institution_type': 'highschool', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Turbo', 'phone_number': '+254532312020', 'email': 'principal@turbohigh.ac.ke', 'principal_name': 'Mr. Ezekiel Kibet', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Eldoret', 'account_number': 'ACC1000070', 'account_name': 'Turbo High School', 'is_active': True},
            {'name': "Moi Girls School Eldoret", 'institution_type': 'highschool', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret North', 'phone_number': '+254532312030', 'email': 'principal@moigirlseldoret.ac.ke', 'principal_name': 'Mrs. Joyce Chepkemoi', 'bank_name': 'Equity Bank', 'bank_branch': 'Eldoret', 'account_number': 'ACC1000071', 'account_name': 'Moi Girls School Eldoret', 'is_active': True},
            {'name': "Kapropita Girls High School", 'institution_type': 'highschool', 'county_name': 'Baringo', 'county_code': '030', 'sub_county': 'Baringo Central', 'phone_number': '+254542412001', 'email': 'principal@kapropita.ac.ke', 'principal_name': 'Mrs. Agnes Chebet', 'bank_name': 'Family Bank', 'bank_branch': 'Kabarnet', 'account_number': 'ACC1000072', 'account_name': 'Kapropita Girls High School', 'is_active': True},
            {'name': "Kapsabet Boys High School", 'institution_type': 'highschool', 'county_name': 'Nandi', 'county_code': '030', 'sub_county': 'Tinderet', 'phone_number': '+254542312010', 'email': 'principal@kapsabethigh.ac.ke', 'principal_name': 'Mr. Timothy Kosgei', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kapsabet', 'account_number': 'ACC1000073', 'account_name': 'Kapsabet Boys High School', 'is_active': True},
            {'name': "Kapsabet Girls High School", 'institution_type': 'highschool', 'county_name': 'Nandi', 'county_code': '030', 'sub_county': 'Tinderet', 'phone_number': '+254542312011', 'email': 'principal@kapsabetgirls.ac.ke', 'principal_name': 'Mrs. Naomi Sigei', 'bank_name': 'Equity Bank', 'bank_branch': 'Kapsabet', 'account_number': 'ACC1000074', 'account_name': 'Kapsabet Girls High School', 'is_active': True},
            {'name': "Kakamega Girls High School", 'institution_type': 'highschool', 'county_name': 'Kakamega', 'county_code': '031', 'sub_county': 'Lurambi', 'phone_number': '+254562312020', 'email': 'principal@kakamegagirls.ac.ke', 'principal_name': 'Mrs. Winnie Khisa', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kakamega', 'account_number': 'ACC1000075', 'account_name': 'Kakamega Girls High School', 'is_active': True},
            {'name': "St. Anthony's Boys High School Kitale", 'institution_type': 'highschool', 'county_name': 'Trans Nzoia', 'county_code': '026', 'sub_county': 'Kitale', 'phone_number': '+254542512001', 'email': 'principal@stanthonyskitale.ac.ke', 'principal_name': 'Br. Philip Wafula', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kitale', 'account_number': 'ACC1000076', 'account_name': "St. Anthony's Boys High School", 'is_active': True},
            {'name': "Kitale High School", 'institution_type': 'highschool', 'county_name': 'Trans Nzoia', 'county_code': '026', 'sub_county': 'Kitale', 'phone_number': '+254542512002', 'email': 'principal@kitalehigh.ac.ke', 'principal_name': 'Mr. Reuben Simiyu', 'bank_name': 'Equity Bank', 'bank_branch': 'Kitale', 'account_number': 'ACC1000077', 'account_name': 'Kitale High School', 'is_active': True},
            {'name': "Menengai High School", 'institution_type': 'highschool', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town West', 'phone_number': '+254512312080', 'email': 'principal@menengaihigh.ac.ke', 'principal_name': 'Mr. David Kamau', 'bank_name': 'Family Bank', 'bank_branch': 'Nakuru', 'account_number': 'ACC1000078', 'account_name': 'Menengai High School', 'is_active': True},
            {'name': "Machakos Boys High School", 'institution_type': 'highschool', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312020', 'email': 'principal@machakosbhigh.ac.ke', 'principal_name': 'Mr. James Musyoka', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Machakos', 'account_number': 'ACC1000079', 'account_name': 'Machakos Boys High School', 'is_active': True},
            {'name': "Nguutani Secondary School", 'institution_type': 'highschool', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Yatta', 'phone_number': '+254442312030', 'email': 'principal@nguutanisec.ac.ke', 'principal_name': 'Mr. Isaac Nthenge', 'bank_name': 'Equity Bank', 'bank_branch': 'Machakos', 'account_number': 'ACC1000080', 'account_name': 'Nguutani Secondary School', 'is_active': True},
        ]

    # =========================================================
    # UNIVERSITIES
    # =========================================================
    def _universities(self):
        return [
            # ── PUBLIC UNIVERSITIES ────────────────────────────────
            {'name': 'University of Nairobi', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202714888', 'email': 'registrar@uonbi.ac.ke', 'principal_name': 'Prof. Stephen Kiama (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'University Branch', 'account_number': 'UACC100001', 'account_name': 'University of Nairobi', 'postal_address': 'P.O. Box 30197-00100, Nairobi', 'is_active': True},
            {'name': 'Kenyatta University', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Ruiru', 'phone_number': '+254672312101', 'email': 'registrar@ku.ac.ke', 'principal_name': 'Prof. Paul Wainaina (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Thika Road', 'account_number': 'UACC100002', 'account_name': 'Kenyatta University', 'postal_address': 'P.O. Box 43844-00100, Nairobi', 'is_active': True},
            {'name': 'Jomo Kenyatta University of Agriculture and Technology (JKUAT)', 'institution_type': 'university', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Juja', 'phone_number': '+254672312201', 'email': 'registrar@jkuat.ac.ke', 'principal_name': 'Prof. Victoria Wambua (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'JKUAT', 'account_number': 'UACC100003', 'account_name': 'JKUAT', 'postal_address': 'P.O. Box 62000-00200, Nairobi', 'is_active': True},
            {'name': 'Moi University', 'institution_type': 'university', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret East', 'phone_number': '+254532312301', 'email': 'registrar@mu.ac.ke', 'principal_name': 'Prof. Laban Ayiro (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Eldoret', 'account_number': 'UACC100004', 'account_name': 'Moi University', 'postal_address': 'P.O. Box 3900-30100, Eldoret', 'is_active': True},
            {'name': 'Maseno University', 'institution_type': 'university', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Seme', 'phone_number': '+254572312301', 'email': 'registrar@maseno.ac.ke', 'principal_name': 'Prof. Julius Ogeng\'o (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Kisumu', 'account_number': 'UACC100005', 'account_name': 'Maseno University', 'postal_address': 'P.O. Box 333-40105, Maseno', 'is_active': True},
            {'name': 'Egerton University', 'institution_type': 'university', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Njoro', 'phone_number': '+254512312401', 'email': 'registrar@egerton.ac.ke', 'principal_name': 'Prof. Isaac Kibwage (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nakuru', 'account_number': 'UACC100006', 'account_name': 'Egerton University', 'postal_address': 'P.O. Box 536-20115, Egerton', 'is_active': True},
            {'name': 'Dedan Kimathi University of Technology', 'institution_type': 'university', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312401', 'email': 'registrar@dkut.ac.ke', 'principal_name': 'Prof. Isaac Kamau (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Nyeri', 'account_number': 'UACC100007', 'account_name': 'Dedan Kimathi University', 'postal_address': 'P.O. Box 657-10100, Nyeri', 'is_active': True},
            {'name': "Murang'a University of Technology", 'institution_type': 'university', 'county_name': "Murang'a", 'county_code': '022', 'sub_county': "Murang'a Town", 'phone_number': '+254720400001', 'email': 'info@mut.ac.ke', 'principal_name': 'Prof. John Kamau Mwangi (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': "Murang'a", 'account_number': 'UACC100008', 'account_name': "Murang'a University of Technology", 'postal_address': "P.O. Box 75-10200, Murang'a", 'is_active': True},
            {'name': 'Karatina University', 'institution_type': 'university', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312501', 'email': 'registrar@karu.ac.ke', 'principal_name': 'Prof. Mary Wanjiku (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Karatina', 'account_number': 'UACC100009', 'account_name': 'Karatina University', 'postal_address': 'P.O. Box 1957-10101, Karatina', 'is_active': True},
            {'name': 'Kibabii University', 'institution_type': 'university', 'county_name': 'Bungoma', 'county_code': '039', 'sub_county': 'Kanduyi', 'phone_number': '+254553312001', 'email': 'registrar@kibabiiuniversity.ac.ke', 'principal_name': 'Prof. Isaac Ipara (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Bungoma', 'account_number': 'UACC100010', 'account_name': 'Kibabii University', 'postal_address': 'P.O. Box 1699-50200, Bungoma', 'is_active': True},
            {'name': 'South Eastern Kenya University (SEKU)', 'institution_type': 'university', 'county_name': 'Kitui', 'county_code': '015', 'sub_county': 'Kitui Central', 'phone_number': '+254462312101', 'email': 'registrar@seku.ac.ke', 'principal_name': 'Prof. Margret Hutchinson (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kitui', 'account_number': 'UACC100011', 'account_name': 'South Eastern Kenya University', 'postal_address': 'P.O. Box 170-90200, Kitui', 'is_active': True},
            {'name': 'Kisii University', 'institution_type': 'university', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312101', 'email': 'registrar@kisiiuniversity.ac.ke', 'principal_name': 'Prof. John Akama (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Kisii', 'account_number': 'UACC100012', 'account_name': 'Kisii University', 'postal_address': 'P.O. Box 408-40200, Kisii', 'is_active': True},
            {'name': 'Laikipia University', 'institution_type': 'university', 'county_name': 'Laikipia', 'county_code': '031', 'sub_county': 'Nyahururu', 'phone_number': '+254512312501', 'email': 'registrar@laikipia.ac.ke', 'principal_name': 'Prof. Paul Rutto (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Nyahururu', 'account_number': 'UACC100013', 'account_name': 'Laikipia University', 'postal_address': 'P.O. Box 1100-20300, Nyahururu', 'is_active': True},
            {'name': 'Pwani University', 'institution_type': 'university', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Kilifi North', 'phone_number': '+254412312101', 'email': 'registrar@pu.ac.ke', 'principal_name': 'Prof. Ahmed Sheikh (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kilifi', 'account_number': 'UACC100014', 'account_name': 'Pwani University', 'postal_address': 'P.O. Box 195-80108, Kilifi', 'is_active': True},
            {'name': 'Rongo University', 'institution_type': 'university', 'county_name': 'Migori', 'county_code': '044', 'sub_county': 'Rongo', 'phone_number': '+254592512101', 'email': 'registrar@rongouniversity.ac.ke', 'principal_name': 'Prof. John Odhiambo (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Migori', 'account_number': 'UACC100015', 'account_name': 'Rongo University', 'postal_address': 'P.O. Box 103-40404, Rongo', 'is_active': True},
            {'name': 'Technical University of Kenya (TUK)', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202312401', 'email': 'registrar@tukenya.ac.ke', 'principal_name': 'Prof. Francis Aduol (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nairobi Central', 'account_number': 'UACC100016', 'account_name': 'Technical University of Kenya', 'postal_address': 'P.O. Box 52428-00200, Nairobi', 'is_active': True},
            {'name': 'Technical University of Mombasa (TUM)', 'institution_type': 'university', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312401', 'email': 'registrar@tum.ac.ke', 'principal_name': 'Prof. Ludovic Ngatia (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Mombasa', 'account_number': 'UACC100017', 'account_name': 'Technical University of Mombasa', 'postal_address': 'P.O. Box 90420-80100, Mombasa', 'is_active': True},
            {'name': 'University of Eldoret', 'institution_type': 'university', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret East', 'phone_number': '+254532312401', 'email': 'registrar@uoeld.ac.ke', 'principal_name': 'Prof. John Chesoli (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Eldoret', 'account_number': 'UACC100018', 'account_name': 'University of Eldoret', 'postal_address': 'P.O. Box 1125-30100, Eldoret', 'is_active': True},
            {'name': 'Chuka University', 'institution_type': 'university', 'county_name': 'Tharaka-Nithi', 'county_code': '016', 'sub_county': 'Chuka/Igambang\'ombe', 'phone_number': '+254642312401', 'email': 'registrar@chuka.ac.ke', 'principal_name': 'Prof. Henry Thaara (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Chuka', 'account_number': 'UACC100019', 'account_name': 'Chuka University', 'postal_address': 'P.O. Box 109-60400, Chuka', 'is_active': True},
            {'name': "Kirinyaga University", 'institution_type': 'university', 'county_name': 'Kirinyaga', 'county_code': '020', 'sub_county': 'Mwea', 'phone_number': '+254602312401', 'email': 'registrar@kyu.ac.ke', 'principal_name': 'Prof. Rosemary Ibutho (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Kerugoya', 'account_number': 'UACC100020', 'account_name': 'Kirinyaga University', 'postal_address': 'P.O. Box 143-10300, Kerugoya', 'is_active': True},

            # ── PRIVATE UNIVERSITIES ───────────────────────────────
            {'name': 'Strathmore University', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Dagoretti North', 'phone_number': '+254703034000', 'email': 'admissions@strathmore.edu', 'principal_name': 'Prof. John Odhiambo (Vice Chancellor)', 'bank_name': 'Barclays Bank Kenya', 'bank_branch': 'Karen', 'account_number': 'UACC100021', 'account_name': 'Strathmore University', 'postal_address': 'P.O. Box 59857-00200, Nairobi', 'is_active': True},
            {'name': 'Daystar University', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Langata', 'phone_number': '+254202713488', 'email': 'admissions@daystar.ac.ke', 'principal_name': 'Prof. Timothy Wachira (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Westlands', 'account_number': 'UACC100022', 'account_name': 'Daystar University', 'postal_address': 'P.O. Box 44400-00100, Nairobi', 'is_active': True},
            {'name': 'United States International University Africa (USIU)', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kasarani', 'phone_number': '+254730116000', 'email': 'admissions@usiu.ac.ke', 'principal_name': 'Prof. Freida Brown (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kasarani', 'account_number': 'UACC100023', 'account_name': 'USIU Africa', 'postal_address': 'P.O. Box 14634-00800, Nairobi', 'is_active': True},
            {'name': 'Mount Kenya University (MKU)', 'institution_type': 'university', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254675312001', 'email': 'registrar@mku.ac.ke', 'principal_name': 'Dr. Simon Gicharu (Founder/Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Thika', 'account_number': 'UACC100024', 'account_name': 'Mount Kenya University', 'postal_address': 'P.O. Box 342-01000, Thika', 'is_active': True},
            {'name': 'Africa Nazarene University (ANU)', 'institution_type': 'university', 'county_name': 'Kajiado', 'county_code': '034', 'sub_county': 'Rongai', 'phone_number': '+254452312201', 'email': 'registrar@anu.ac.ke', 'principal_name': 'Dr. Leah Marangu (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Rongai', 'account_number': 'UACC100025', 'account_name': 'Africa Nazarene University', 'postal_address': 'P.O. Box 53067-00200, Nairobi', 'is_active': True},
            {'name': 'Catholic University of Eastern Africa (CUEA)', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Langata', 'phone_number': '+254202714901', 'email': 'admissions@cuea.edu', 'principal_name': 'Prof. Patrick Mwania (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Karen', 'account_number': 'UACC100026', 'account_name': 'Catholic University of Eastern Africa', 'postal_address': 'P.O. Box 62157-00200, Nairobi', 'is_active': True},
            {'name': 'Adventist University of Africa (AUA)', 'institution_type': 'university', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Kikuyu', 'phone_number': '+254202312501', 'email': 'info@aua.ac.ke', 'principal_name': 'Dr. Emmanuel Banchani (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Kikuyu', 'account_number': 'UACC100027', 'account_name': 'Adventist University of Africa', 'postal_address': 'P.O. Box 2561-00606, Nairobi', 'is_active': True},
            {'name': 'Pan Africa Christian University (PAC)', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kasarani', 'phone_number': '+254202312601', 'email': 'registrar@pac.ac.ke', 'principal_name': 'Rev. Dr. Mark Kariuki (Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Thika Road', 'account_number': 'UACC100028', 'account_name': 'Pan Africa Christian University', 'postal_address': 'P.O. Box 56875-00200, Nairobi', 'is_active': True},
            {'name': 'Gretsa University', 'institution_type': 'university', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254675312101', 'email': 'registrar@gretsa.ac.ke', 'principal_name': 'Prof. Charles Kamau (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Thika', 'account_number': 'UACC100029', 'account_name': 'Gretsa University', 'postal_address': 'P.O. Box 3-01000, Thika', 'is_active': True},
            {'name': 'Zetech University', 'institution_type': 'university', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Ruiru', 'phone_number': '+254722199500', 'email': 'info@zetech.ac.ke', 'principal_name': 'Dr. Esther Gitaari (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Ruiru', 'account_number': 'UACC100030', 'account_name': 'Zetech University', 'postal_address': 'P.O. Box 2768-00100, Nairobi', 'is_active': True},
            {'name': 'KCA University', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kasarani', 'phone_number': '+254202312701', 'email': 'registrar@kca.ac.ke', 'principal_name': 'Dr. David Nzioka (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kasarani', 'account_number': 'UACC100031', 'account_name': 'KCA University', 'postal_address': 'P.O. Box 56808-00200, Nairobi', 'is_active': True},
            {'name': 'Scott Christian University', 'institution_type': 'university', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312201', 'email': 'registrar@scu.ac.ke', 'principal_name': 'Dr. William Mutua (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Machakos', 'account_number': 'UACC100032', 'account_name': 'Scott Christian University', 'postal_address': 'P.O. Box 49-90100, Machakos', 'is_active': True},
            {'name': 'Great Lakes University of Kisumu', 'institution_type': 'university', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312401', 'email': 'registrar@gluk.ac.ke', 'principal_name': 'Prof. George Otieno (Vice Chancellor)', 'bank_name': 'Equity Bank', 'bank_branch': 'Kisumu', 'account_number': 'UACC100033', 'account_name': 'Great Lakes University of Kisumu', 'postal_address': 'P.O. Box 2224-40100, Kisumu', 'is_active': True},
            {'name': 'Baraton University of East Africa', 'institution_type': 'university', 'county_name': 'Nandi', 'county_code': '030', 'sub_county': 'Tinderet', 'phone_number': '+254542312101', 'email': 'registrar@baraton.ac.ke', 'principal_name': 'Dr. Bezalel Maingi (Vice Chancellor)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kapsabet', 'account_number': 'UACC100034', 'account_name': 'Baraton University', 'postal_address': 'P.O. Box 2770-30100, Eldoret', 'is_active': True},
            {'name': 'International Leadership University (ILU)', 'institution_type': 'university', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Kasarani', 'phone_number': '+254722312001', 'email': 'registrar@ilu.ac.ke', 'principal_name': 'Rev. Dr. Samuel Mwangi (Vice Chancellor)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Nairobi', 'account_number': 'UACC100035', 'account_name': 'International Leadership University', 'postal_address': 'P.O. Box 1001-00600, Nairobi', 'is_active': True},
        ]

    # =========================================================
    # COLLEGES & TVETs
    # =========================================================
    def _colleges_and_tvets(self):
        return [
            # ── MEDICAL TRAINING COLLEGES (KMTC) ──────────────────
            {'name': 'Kenya Medical Training College - Nairobi', 'institution_type': 'college', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202312801', 'email': 'nairobi@kmtc.ac.ke', 'principal_name': 'Mr. Daniel Mwangi (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nairobi', 'account_number': 'CACC100001', 'account_name': 'KMTC Nairobi', 'is_active': True},
            {'name': 'Kenya Medical Training College - Mombasa', 'institution_type': 'college', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312801', 'email': 'mombasa@kmtc.ac.ke', 'principal_name': 'Mr. Hassan Mwangola (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Mombasa', 'account_number': 'CACC100002', 'account_name': 'KMTC Mombasa', 'is_active': True},
            {'name': 'Kenya Medical Training College - Kisumu', 'institution_type': 'college', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312501', 'email': 'kisumu@kmtc.ac.ke', 'principal_name': 'Mr. George Onyango (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisumu', 'account_number': 'CACC100003', 'account_name': 'KMTC Kisumu', 'is_active': True},
            {'name': "Kenya Medical Training College - Murang'a", 'institution_type': 'college', 'county_name': "Murang'a", 'county_code': '022', 'sub_county': "Murang'a Town", 'phone_number': '+254720500007', 'email': 'muranga@kmtc.ac.ke', 'principal_name': 'Mr. Benjamin Kariuki (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': "Murang'a", 'account_number': 'CACC100004', 'account_name': "KMTC Murang'a", 'is_active': True},
            {'name': 'Kenya Medical Training College - Nyeri', 'institution_type': 'college', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Nyeri Town', 'phone_number': '+254612312601', 'email': 'nyeri@kmtc.ac.ke', 'principal_name': 'Mrs. Susan Muthoni (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Nyeri', 'account_number': 'CACC100005', 'account_name': 'KMTC Nyeri', 'is_active': True},
            {'name': 'Kenya Medical Training College - Nakuru', 'institution_type': 'college', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town East', 'phone_number': '+254512312601', 'email': 'nakuru@kmtc.ac.ke', 'principal_name': 'Mr. Patrick Mwangi (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Nakuru', 'account_number': 'CACC100006', 'account_name': 'KMTC Nakuru', 'is_active': True},
            {'name': 'Kenya Medical Training College - Embu', 'institution_type': 'college', 'county_name': 'Embu', 'county_code': '014', 'sub_county': 'Embu Town', 'phone_number': '+254682312601', 'email': 'embu@kmtc.ac.ke', 'principal_name': 'Mr. James Gitonga (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Embu', 'account_number': 'CACC100007', 'account_name': 'KMTC Embu', 'is_active': True},

            # ── NATIONAL POLYTECHNICS ──────────────────────────────
            {'name': 'Kenya National Polytechnic - Thika', 'institution_type': 'technical_institute', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254675312501', 'email': 'info@knpthika.ac.ke', 'principal_name': 'Dr. Ruth Wambui (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Thika', 'account_number': 'CACC100008', 'account_name': 'Kenya National Polytechnic Thika', 'is_active': True},
            {'name': 'Mombasa Polytechnic University College', 'institution_type': 'technical_institute', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412312901', 'email': 'info@mombpoly.ac.ke', 'principal_name': 'Prof. Hassan Juma (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Mombasa', 'account_number': 'CACC100009', 'account_name': 'Mombasa Polytechnic', 'is_active': True},

            # ── TEACHERS TRAINING COLLEGES ─────────────────────────
            {"name": "Murang'a Teachers' College", 'institution_type': 'college', 'county_name': "Murang'a", 'county_code': '022', 'sub_county': "Murang'a Town", 'phone_number': '+254720500009', 'email': 'muranga.ttc@tsc.go.ke', 'principal_name': 'Mr. Frederick Njoki (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': "Murang'a", 'account_number': 'CACC100010', 'account_name': "Murang'a Teachers' College", 'is_active': True},
            {'name': "Kagumo Teachers' College", 'institution_type': 'college', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Mathira', 'phone_number': '+254612312701', 'email': 'kagumo.ttc@tsc.go.ke', 'principal_name': 'Mr. Peter Wanjiku (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Karatina', 'account_number': 'CACC100011', 'account_name': "Kagumo Teachers' College", 'is_active': True},
            {'name': "Highridge Teachers' College", 'institution_type': 'college', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Westlands', 'phone_number': '+254202312901', 'email': 'highridge.ttc@tsc.go.ke', 'principal_name': 'Mrs. Grace Wanjiku (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Westlands', 'account_number': 'CACC100012', 'account_name': "Highridge Teachers' College", 'is_active': True},
            {'name': "Kisii Teachers' College", 'institution_type': 'college', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312701', 'email': 'kisii.ttc@tsc.go.ke', 'principal_name': 'Mr. Alphonce Omari (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisii', 'account_number': 'CACC100013', 'account_name': "Kisii Teachers' College", 'is_active': True},
            {'name': "Machakos Teachers' College", 'institution_type': 'college', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312701', 'email': 'machakos.ttc@tsc.go.ke', 'principal_name': 'Mr. Isaac Muli (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Machakos', 'account_number': 'CACC100014', 'account_name': "Machakos Teachers' College", 'is_active': True},
            {'name': "Kilimambogo Teachers' College", 'institution_type': 'college', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254672312801', 'email': 'kilimambogo.ttc@tsc.go.ke', 'principal_name': 'Mrs. Martha Kamau (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Thika', 'account_number': 'CACC100015', 'account_name': "Kilimambogo Teachers' College", 'is_active': True},

            # ── TECHNICAL TRAINING INSTITUTES (TTIs) ──────────────
            {'name': 'Nairobi Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Nairobi', 'county_code': '047', 'sub_county': 'Starehe', 'phone_number': '+254202313001', 'email': 'nairobi.tti@tvet.go.ke', 'principal_name': 'Mr. Andrew Odhiambo (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nairobi', 'account_number': 'CACC100016', 'account_name': 'Nairobi TTI', 'is_active': True},
            {'name': "Murang'a Technical Training Institute", 'institution_type': 'technical_institute', 'county_name': "Murang'a", 'county_code': '022', 'sub_county': "Murang'a Town", 'phone_number': '+254720500001', 'email': 'muranga.tti@tvet.go.ke', 'principal_name': 'Mr. Isaac Njoroge (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': "Murang'a", 'account_number': 'CACC100017', 'account_name': "Murang'a TTI", 'is_active': True},
            {'name': 'Mombasa Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Mombasa', 'county_code': '001', 'sub_county': 'Mvita', 'phone_number': '+254412313101', 'email': 'mombasa.tti@tvet.go.ke', 'principal_name': 'Mr. Rashid Omar (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Mombasa', 'account_number': 'CACC100018', 'account_name': 'Mombasa TTI', 'is_active': True},
            {'name': 'Kisumu Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kisumu', 'county_code': '040', 'sub_county': 'Kisumu Central', 'phone_number': '+254572312601', 'email': 'kisumu.tti@tvet.go.ke', 'principal_name': 'Mr. David Ouko (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kisumu', 'account_number': 'CACC100019', 'account_name': 'Kisumu TTI', 'is_active': True},
            {'name': 'Nakuru Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Nakuru', 'county_code': '032', 'sub_county': 'Nakuru Town East', 'phone_number': '+254512312801', 'email': 'nakuru.tti@tvet.go.ke', 'principal_name': 'Mr. Joseph Mwangi (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Nakuru', 'account_number': 'CACC100020', 'account_name': 'Nakuru TTI', 'is_active': True},
            {'name': 'Eldoret Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Uasin Gishu', 'county_code': '027', 'sub_county': 'Eldoret East', 'phone_number': '+254532312601', 'email': 'eldoret.tti@tvet.go.ke', 'principal_name': 'Mr. Ezekiel Koech (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Eldoret', 'account_number': 'CACC100021', 'account_name': 'Eldoret TTI', 'is_active': True},
            {'name': 'Nyeri Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Nyeri', 'county_code': '037', 'sub_county': 'Nyeri Town', 'phone_number': '+254612312801', 'email': 'nyeri.tti@tvet.go.ke', 'principal_name': 'Mr. James Gatheru (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Nyeri', 'account_number': 'CACC100022', 'account_name': 'Nyeri TTI', 'is_active': True},
            {'name': 'Embu Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Embu', 'county_code': '014', 'sub_county': 'Embu Town', 'phone_number': '+254682312801', 'email': 'embu.tti@tvet.go.ke', 'principal_name': 'Mr. Peter Nthiga (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Embu', 'account_number': 'CACC100023', 'account_name': 'Embu TTI', 'is_active': True},
            {'name': 'Meru Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Meru', 'county_code': '021', 'sub_county': 'Imenti North', 'phone_number': '+254642312801', 'email': 'meru.tti@tvet.go.ke', 'principal_name': 'Mr. Wilfred Mugambi (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Meru', 'account_number': 'CACC100024', 'account_name': 'Meru TTI', 'is_active': True},
            {'name': 'Kitui Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kitui', 'county_code': '015', 'sub_county': 'Kitui Central', 'phone_number': '+254462312801', 'email': 'kitui.tti@tvet.go.ke', 'principal_name': 'Mr. Samuel Nguli (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kitui', 'account_number': 'CACC100025', 'account_name': 'Kitui TTI', 'is_active': True},
            {'name': 'Machakos Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Machakos', 'county_code': '016', 'sub_county': 'Machakos Town', 'phone_number': '+254442312801', 'email': 'machakos.tti@tvet.go.ke', 'principal_name': 'Mr. John Mutua (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Machakos', 'account_number': 'CACC100026', 'account_name': 'Machakos TTI', 'is_active': True},
            {'name': 'Kisii Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kisii', 'county_code': '045', 'sub_county': 'Kisii Central', 'phone_number': '+254582312801', 'email': 'kisii.tti@tvet.go.ke', 'principal_name': 'Mr. Kenneth Ongeri (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kisii', 'account_number': 'CACC100027', 'account_name': 'Kisii TTI', 'is_active': True},
            {'name': 'Kakamega Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kakamega', 'county_code': '031', 'sub_county': 'Lurambi', 'phone_number': '+254562312801', 'email': 'kakamega.tti@tvet.go.ke', 'principal_name': 'Mr. Michael Wanyonyi (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Kakamega', 'account_number': 'CACC100028', 'account_name': 'Kakamega TTI', 'is_active': True},
            {'name': 'Thika Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kiambu', 'county_code': '036', 'sub_county': 'Thika Town', 'phone_number': '+254675312801', 'email': 'thika.tti@tvet.go.ke', 'principal_name': 'Mrs. Lucy Kariuki (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Thika', 'account_number': 'CACC100029', 'account_name': 'Thika TTI', 'is_active': True},
            {'name': 'Voi Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Taita-Taveta', 'county_code': '006', 'sub_county': 'Voi', 'phone_number': '+254432312001', 'email': 'voi.tti@tvet.go.ke', 'principal_name': 'Mr. James Mwangangi (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Voi', 'account_number': 'CACC100030', 'account_name': 'Voi TTI', 'is_active': True},
            {'name': 'Malindi Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kilifi', 'county_code': '003', 'sub_county': 'Malindi', 'phone_number': '+254422312801', 'email': 'malindi.tti@tvet.go.ke', 'principal_name': 'Mr. Salim Mwakio (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Malindi', 'account_number': 'CACC100031', 'account_name': 'Malindi TTI', 'is_active': True},
            {'name': 'Garissa Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Garissa', 'county_code': '007', 'sub_county': 'Garissa Township', 'phone_number': '+254462512001', 'email': 'garissa.tti@tvet.go.ke', 'principal_name': 'Mr. Hussein Abdi (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Garissa', 'account_number': 'CACC100032', 'account_name': 'Garissa TTI', 'is_active': True},
            {'name': 'Bungoma Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Bungoma', 'county_code': '039', 'sub_county': 'Kanduyi', 'phone_number': '+254553312801', 'email': 'bungoma.tti@tvet.go.ke', 'principal_name': 'Mr. Paul Wafula (Principal)', 'bank_name': 'Kenya Commercial Bank', 'bank_branch': 'Bungoma', 'account_number': 'CACC100033', 'account_name': 'Bungoma TTI', 'is_active': True},
            {'name': 'Nyamira Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Nyamira', 'county_code': '046', 'sub_county': 'Manga', 'phone_number': '+254582412801', 'email': 'nyamira.tti@tvet.go.ke', 'principal_name': 'Mr. Francis Onsongo (Principal)', 'bank_name': 'Equity Bank', 'bank_branch': 'Nyamira', 'account_number': 'CACC100034', 'account_name': 'Nyamira TTI', 'is_active': True},
            {'name': 'Kajiado Technical Training Institute', 'institution_type': 'technical_institute', 'county_name': 'Kajiado', 'county_code': '034', 'sub_county': 'Kajiado North', 'phone_number': '+254452312801', 'email': 'kajiado.tti@tvet.go.ke', 'principal_name': 'Mr. David Tipape (Principal)', 'bank_name': 'Co-operative Bank', 'bank_branch': 'Kajiado', 'account_number': 'CACC100035', 'account_name': 'Kajiado TTI', 'is_active': True},
        ]