# Generated by Django 5.2.4 on 2025-10-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='system_county',
            field=models.CharField(default="Murang'a", help_text='County this bursary system instance is configured for.', max_length=100),
        ),
    ]
