# Generated by Django 5.2.8 on 2025-11-17 19:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_county_system_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_text', models.TextField(help_text='Share your experience with the bursary program')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate your experience from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Display on public page')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='main_application.application')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_public_testimonials', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('bulk_cheque', 'Bulk Cheque'), ('eft', 'Electronic Funds Transfer')], default='cheque', max_length=20)),
                ('reference_number', models.CharField(help_text='Payment reference/transaction number', max_length=100, unique=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('disbursement_date', models.DateField(help_text='Date payment was made')),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('actual_receipt_date', models.DateField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_received_by_institution', models.BooleanField(default=False)),
                ('institution_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_confirmation_date', models.DateField(blank=True, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='main_application.allocation')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='main_application.applicant')),
                ('bulk_cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_disbursements', to='main_application.bulkcheque')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='main_application.fiscalyear')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_disbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-disbursement_date'],
                'indexes': [models.Index(fields=['fiscal_year', 'status'], name='main_applic_fiscal__45a82f_idx'), models.Index(fields=['disbursement_date'], name='main_applic_disburs_35a7a1_idx'), models.Index(fields=['reference_number'], name='main_applic_referen_7ca66d_idx')],
            },
        ),
    ]
