# Generated by Django 5.2.8 on 2025-11-17 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_testimonial_disbursement'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=500, unique=True)),
                ('url_name', models.CharField(blank=True, max_length=200, null=True)),
                ('view_name', models.CharField(blank=True, max_length=200, null=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visit_count'],
            },
        ),
        migrations.CreateModel(
            name='UserURLVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('url_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to='main_application.urlvisit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
