# Generated by Django 5.2.8 on 2025-11-17 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_urlvisit_userurlvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('xss', 'Cross-Site Scripting (XSS)'), ('path_traversal', 'Path Traversal'), ('code_injection', 'Code Injection'), ('brute_force', 'Brute Force Attack'), ('credential_stuffing', 'Credential Stuffing'), ('rate_limit', 'Rate Limit Exceeded'), ('suspicious_agent', 'Suspicious User Agent'), ('phishing', 'Phishing Attempt'), ('malware', 'Malware Detection'), ('ddos', 'DDoS Attack'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_threats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_threats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='main_applic_detecte_f172c8_idx'), models.Index(fields=['severity', '-detected_at'], name='main_applic_severit_d07a5b_idx'), models.Index(fields=['ip_address', '-detected_at'], name='main_applic_ip_addr_43476b_idx'), models.Index(fields=['resolved', '-detected_at'], name='main_applic_resolve_8688c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('unusual_access_pattern', 'Unusual Access Pattern'), ('rapid_data_access', 'Rapid Data Access'), ('failed_authorization', 'Multiple Failed Authorization Attempts'), ('data_exfiltration', 'Possible Data Exfiltration'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('unusual_location', 'Access from Unusual Location'), ('unusual_time', 'Access at Unusual Time'), ('multiple_devices', 'Multiple Devices Simultaneously'), ('phishing_link_click', 'Phishing Link Click'), ('account_sharing', 'Possible Account Sharing')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('investigated', models.BooleanField(default=False)),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suspicious Activities',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='main_applic_detecte_5f4031_idx'), models.Index(fields=['user', '-detected_at'], name='main_applic_user_id_19d2fa_idx'), models.Index(fields=['investigated', '-detected_at'], name='main_applic_investi_866e78_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='main_applic_user_id_5f677b_idx'), models.Index(fields=['-last_activity'], name='main_applic_last_ac_4a3729_idx')],
            },
        ),
    ]
